#!/bin/sh
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/libavrxmega6g1-4qt-k-0rs.a ./3rd-party/Atmel/xmega/lib/qtouch/
cp $1/xmega/utils/bit_handling/clz_ctz.h ./3rd-party/Atmel/xmega/utils/bit_handling/
cp $1/xmega/utils/status_codes.h ./3rd-party/Atmel/xmega/utils/
cp $1/xmega/utils/assembler.h ./3rd-party/Atmel/xmega/utils/
cp $1/xmega/utils/compiler.h ./3rd-party/Atmel/xmega/utils/
cp $1/xmega/utils/assembler/gas.h ./3rd-party/Atmel/xmega/utils/assembler/
cp $1/xmega/utils/progmem.h ./3rd-party/Atmel/xmega/utils/
cp $1/xmega/utils/preprocessor/stringz.h ./3rd-party/Atmel/xmega/utils/preprocessor/
cp $1/xmega/utils/preprocessor/tpaste.h ./3rd-party/Atmel/xmega/utils/preprocessor/
cp $1/xmega/utils/preprocessor/mrepeat.h ./3rd-party/Atmel/xmega/utils/preprocessor/
cp $1/xmega/utils/preprocessor/preprocessor.h ./3rd-party/Atmel/xmega/utils/preprocessor/
cp $1/xmega/drivers/sleep/sleep.h ./3rd-party/Atmel/xmega/drivers/sleep/
cp $1/xmega/drivers/usart/usart.c ./3rd-party/Atmel/xmega/drivers/usart/
cp $1/xmega/drivers/usart/usart.h ./3rd-party/Atmel/xmega/drivers/usart/
cp $1/xmega/drivers/rtc32/rtc32.c ./3rd-party/Atmel/xmega/drivers/rtc32/
cp $1/xmega/drivers/rtc32/rtc32.h ./3rd-party/Atmel/xmega/drivers/rtc32/
cp $1/xmega/drivers/nvm/nvm.c ./3rd-party/Atmel/xmega/drivers/nvm/
cp $1/xmega/drivers/nvm/nvm_asm.s ./3rd-party/Atmel/xmega/drivers/nvm/
cp $1/xmega/drivers/nvm/nvm.h ./3rd-party/Atmel/xmega/drivers/nvm/
cp $1/xmega/drivers/cpu/ccp.h ./3rd-party/Atmel/xmega/drivers/cpu/
cp $1/xmega/drivers/cpu/xmega_reset_cause.h ./3rd-party/Atmel/xmega/drivers/cpu/
cp $1/xmega/drivers/cpu/ccp.s ./3rd-party/Atmel/xmega/drivers/cpu/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/qt_asm_xmega.s ./3rd-party/Atmel/xmega/drivers/qtouch/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/touch_api.h ./3rd-party/Atmel/xmega/drivers/qtouch/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/touch.c ./3rd-party/Atmel/xmega/drivers/qtouch/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/touch_qt_config.h ./3rd-party/Atmel/xmega/drivers/qtouch/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/qtouch/license.txt ./3rd-party/Atmel/xmega/drivers/qtouch/
cp $1/xmega/drivers/pmic/pmic.h ./3rd-party/Atmel/xmega/drivers/pmic/
cp $1/xmega/drivers/tc/tc.h ./3rd-party/Atmel/xmega/drivers/tc/
cp $1/xmega/drivers/tc/tc.c ./3rd-party/Atmel/xmega/drivers/tc/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/atxmega256a3bu_xmega_a3bu_xplained/conf_st7565r.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/boards/xmega_a3bu_xplained/board_config/conf_board.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/boards/xmega_a3bu_xplained/led.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/atxmega256a3bu_xmega_a3bu_xplained/conf_rtc32.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/boards/xmega_a3bu_xplained/xmega_a3bu_xplained.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/boards/xmega_a3bu_xplained/init.c ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/atxmega256a3bu_xmega_a3bu_xplained/conf_clock.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/atxmega256a3bu_xmega_a3bu_xplained/conf_usart_spi.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/xmega/applications/xmega_a3bu_xplained_demo/atxmega256a3bu_xmega_a3bu_xplained/conf_sleepmgr.h ./3rd-party/Atmel/xmega/boards/xmega_a3bu_xplained/
cp $1/common/services/sleepmgr/sleepmgr.h ./3rd-party/Atmel/common/services/sleepmgr/
cp $1/common/services/sleepmgr/xmega/sleepmgr.h ./3rd-party/Atmel/common/services/sleepmgr/xmega/
cp $1/common/services/sleepmgr/xmega/sleepmgr.c ./3rd-party/Atmel/common/services/sleepmgr/xmega/
cp $1/common/services/ioport/xmega/ioport_compat.c ./3rd-party/Atmel/common/services/ioport/xmega/
cp $1/common/services/ioport/xmega/ioport_compat.h ./3rd-party/Atmel/common/services/ioport/xmega/
cp $1/common/services/ioport/xmega/ioport.h ./3rd-party/Atmel/common/services/ioport/xmega/
cp $1/common/services/ioport/ioport.h ./3rd-party/Atmel/common/services/ioport/
cp $1/common/services/delay/xmega/cycle_counter.h ./3rd-party/Atmel/common/services/delay/xmega/
cp $1/common/services/delay/delay.h ./3rd-party/Atmel/common/services/delay/
cp $1/common/services/spi/usart_spi.h ./3rd-party/Atmel/common/services/spi/
cp $1/common/services/spi/xmega_usart_spi/usart_spi.h ./3rd-party/Atmel/common/services/spi/xmega_usart_spi/
cp $1/common/services/spi/xmega_usart_spi/usart_spi.c ./3rd-party/Atmel/common/services/spi/xmega_usart_spi/
cp $1/common/services/gpio/xmega_gpio/xmega_gpio.h ./3rd-party/Atmel/common/services/gpio/xmega_gpio/
cp $1/common/services/gpio/gpio.h ./3rd-party/Atmel/common/services/gpio/
cp $1/common/services/clock/osc.h ./3rd-party/Atmel/common/services/clock/
cp $1/common/services/clock/sysclk.h ./3rd-party/Atmel/common/services/clock/
cp $1/common/services/clock/xmega/sysclk.c ./3rd-party/Atmel/common/services/clock/xmega/
cp $1/common/services/clock/xmega/osc.h ./3rd-party/Atmel/common/services/clock/xmega/
cp $1/common/services/clock/xmega/sysclk.h ./3rd-party/Atmel/common/services/clock/xmega/
cp $1/common/services/clock/xmega/pll.h ./3rd-party/Atmel/common/services/clock/xmega/
cp $1/common/services/clock/pll.h ./3rd-party/Atmel/common/services/clock/
cp $1/common/utils/parts.h ./3rd-party/Atmel/common/utils/
cp $1/common/utils/interrupt.h ./3rd-party/Atmel/common/utils/
cp $1/common/utils/interrupt/interrupt_avr8.h ./3rd-party/Atmel/common/utils/interrupt/
cp $1/common/boards/board.h ./3rd-party/Atmel/common/boards/
cp $1/common/components/display/st7565r/st7565r.c ./3rd-party/Atmel/common/components/display/st7565r/
cp $1/common/components/display/st7565r/st7565r.h ./3rd-party/Atmel/common/components/display/st7565r/
